##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /       

module Twilio
  module REST
    class Preview < Domain
      class Insights < Version
        class CallContext < InstanceContext
          class MetricsList < ListResource
            ##
            # Initialize the MetricsList
            # @param [Version] version Version that contains the resource
            # @param [String] sid The sid
            
            # @return [MetricsList] MetricsList
            def initialize(version, sid: nil)
              super(version)
              
              # Path Solution
              @solution = {
                  sid: sid
              }
              @uri = "/Calls/#{@solution[:call_sid]}/Metrics"
            end
            
            ##
            # Lists MetricsInstance records from the API as a list.
            # Unlike stream(), this operation is eager and will load `limit` records into
            # memory before returning.
            # @param [String] call_sid The call_sid
            # @param [Integer] limit Upper limit for the number of records to return. stream()
            #                   guarantees to never return more than limit.  Default is no limit
            # @param [Integer] page_size Number of records to fetch per request, when not set will                      use
            #  the default value of 50 records.  If no page_size is                      defined
            #  but a limit is defined, stream() will attempt to read                      the
            #  limit with the most efficient page size,                      i.e. min(limit, 1000)
            
            # @return [Array] Array of up to limit results
            def list(call_sid: nil, limit: nil, page_size: nil)
              self.stream(
                  call_sid: call_sid,
                  limit: limit,
                  page_size: page_size
              ).entries
            end
            
            ##
            # Streams MetricsInstance records from the API as an Enumerable.
            # This operation lazily loads records as efficiently as possible until the limit
            # is reached.
            # @param [String] call_sid The call_sid
            # @param [Integer] limit Upper limit for the number of records to return.                  stream()
            #  guarantees to never return more than limit.                  Default is no limit
            # @param [Integer] page_size Number of records to fetch per request, when                      not set will use
            #  the default value of 50 records.                      If no page_size is defined
            #                       but a limit is defined, stream() will attempt to                      read the
            #  limit with the most efficient page size,                       i.e. min(limit, 1000)
            
            # @return [Enumerable] Enumerable that will yield up to limit results
            def stream(call_sid: nil, limit: nil, page_size: nil)
              limits = @version.read_limits(limit, page_size)
              
              page = self.page(
                  call_sid: call_sid,
                  page_size: limits['page_size'],
              )
              
              @version.stream(page, limit: limits['limit'], page_limit: limits['page_limit'])
            end
            
            ##
            # When passed a block, yields MetricsInstance records from the API.
            # This operation lazily loads records as efficiently as possible until the limit
            # is reached.
            # @param [String] call_sid The call_sid
            # @param [Integer] limit Upper limit for the number of records to return.                  stream()
            #  guarantees to never return more than limit.                  Default is no limit
            # @param [Integer] page_size Number of records to fetch per request, when                       not set will use
            #  the default value of 50 records.                      If no page_size is defined
            #                       but a limit is defined, stream() will attempt to read the
            #                       limit with the most efficient page size, i.e. min(limit, 1000)
            def each
              limits = @version.read_limits
              
              page = self.page(
                  page_size: limits['page_size'],
              )
              
              @version.stream(page,
                              limit: limits['limit'],
                              page_limit: limits['page_limit']).each {|x| yield x}
            end
            
            ##
            # Retrieve a single page of MetricsInstance records from the API.
            # Request is executed immediately.
            # @param [String] call_sid The call_sid
            # @param [String] page_token PageToken provided by the API
            # @param [Integer] page_number Page Number, this value is simply for client state
            # @param [Integer] page_size Number of records to return, defaults to 50
            
            # @return [Page] Page of MetricsInstance
            def page(call_sid: nil, page_token: nil, page_number: nil, page_size: nil)
              params = {
                  'CallSid' => call_sid,
                  'PageToken' => page_token,
                  'Page' => page_number,
                  'PageSize' => page_size,
              }
              response = @version.page(
                  'GET',
                  @uri,
                  params
              )
              return MetricsPage.new(@version, response, @solution)
            end
            
            ##
            # Provide a user friendly representation
            def to_s
              '#<Twilio.Preview.Insights.MetricsList>'
            end
          end
        
          class MetricsPage < Page
            ##
            # Initialize the MetricsPage
            # @param [Version] version Version that contains the resource
            # @param [Response] response Response from the API
            # @param [Hash] solution Path solution for the resource
            # @param [String] sid The sid
            
            # @return [MetricsPage] MetricsPage
            def initialize(version, response, solution)
              super(version, response)
              
              # Path Solution
              @solution = solution
            end
            
            ##
            # Build an instance of MetricsInstance
            # @param [Hash] payload Payload response from the API
            
            # @return [MetricsInstance] MetricsInstance
            def get_instance(payload)
              return MetricsInstance.new(
                  @version,
                  payload,
                  sid: @solution['sid'],
              )
            end
            
            ##
            # Provide a user friendly representation
            def to_s
              '<Twilio.Preview.Insights.MetricsPage>'
            end
          end
        
          class MetricsInstance < InstanceResource
            ##
            # Initialize the MetricsInstance
            # @param [Version] version Version that contains the resource
            # @param [Hash] payload payload that contains response from Twilio
            # @param [String] sid The sid
            
            # @return [MetricsInstance] MetricsInstance
            def initialize(version, payload, sid: nil)
              super(version)
              
              # Marshaled Properties
              @properties = {
                  'call_sid' => payload['call_sid'],
                  'total_bytes_received' => payload['total_bytes_received'].to_i,
                  'total_packets_received' => payload['total_packets_received'].to_i,
                  'total_bytes_sent' => payload['total_bytes_sent'].to_i,
                  'mos' => payload['mos'],
                  'timestamp' => Twilio.deserialize_iso8601(payload['timestamp']),
                  'total_packets_sent' => payload['total_packets_sent'].to_i,
                  'audio_level_in' => payload['audio_level_in'].to_i,
                  'audio_level_out' => payload['audio_level_out'].to_i,
                  'packets_received' => payload['packets_received'].to_i,
                  'jitter' => payload['jitter'].to_i,
                  'timestamp_ms' => payload['timestamp_ms'],
                  'rtt' => payload['rtt'].to_i,
                  'packets_lost' => payload['packets_lost'].to_i,
                  'total_packets_lost' => payload['total_packets_lost'].to_i,
                  'packets_lost_fraction' => payload['packets_lost_fraction'],
              }
            end
            
            def call_sid
              @properties['call_sid']
            end
            
            def total_bytes_received
              @properties['total_bytes_received']
            end
            
            def total_packets_received
              @properties['total_packets_received']
            end
            
            def total_bytes_sent
              @properties['total_bytes_sent']
            end
            
            def mos
              @properties['mos']
            end
            
            def timestamp
              @properties['timestamp']
            end
            
            def total_packets_sent
              @properties['total_packets_sent']
            end
            
            def audio_level_in
              @properties['audio_level_in']
            end
            
            def audio_level_out
              @properties['audio_level_out']
            end
            
            def packets_received
              @properties['packets_received']
            end
            
            def jitter
              @properties['jitter']
            end
            
            def timestamp_ms
              @properties['timestamp_ms']
            end
            
            def rtt
              @properties['rtt']
            end
            
            def packets_lost
              @properties['packets_lost']
            end
            
            def total_packets_lost
              @properties['total_packets_lost']
            end
            
            def packets_lost_fraction
              @properties['packets_lost_fraction']
            end
            
            ##
            # Provide a user friendly representation
            def to_s
              "<Twilio.Preview.Insights.MetricsInstance>"
            end
          end
        end
      end
    end
  end
end