##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /       

module Twilio
  module REST
    class Preview
      class Insights < Version
        ##
        # Initialize the Insights version of Preview
        def initialize(domain)
          super
          @version = 'insights'
          @calls = nil
        end
        
        def calls(sid=:unset)
          if sid == :unset
            @calls ||= CallList.new self
          else
            CallContext.new(self, sid)
          end
        end
        
        ##
        # Provide a user friendly representation
        def to_s
          #<Twilio::REST::Preview::Insights>
        end
      end
    end
  end
end