##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /       

module Twilio
  module REST
    class Preview < Domain
      class Insights < Version
        class CallList < ListResource
          ##
          # Initialize the CallList
          # @param [Version] version Version that contains the resource
          
          # @return [CallList] CallList
          def initialize(version)
            super(version)
            
            # Path Solution
            @solution = {}
          end
          
          ##
          # Provide a user friendly representation
          def to_s
            '#<Twilio.Preview.Insights.CallList>'
          end
        end
      
        class CallPage < Page
          ##
          # Initialize the CallPage
          # @param [Version] version Version that contains the resource
          # @param [Response] response Response from the API
          # @param [Hash] solution Path solution for the resource
          
          # @return [CallPage] CallPage
          def initialize(version, response, solution)
            super(version, response)
            
            # Path Solution
            @solution = solution
          end
          
          ##
          # Build an instance of CallInstance
          # @param [Hash] payload Payload response from the API
          
          # @return [CallInstance] CallInstance
          def get_instance(payload)
            return CallInstance.new(
                @version,
                payload,
            )
          end
          
          ##
          # Provide a user friendly representation
          def to_s
            '<Twilio.Preview.Insights.CallPage>'
          end
        end
      
        class CallInstance < InstanceResource
          ##
          # Initialize the CallInstance
          # @param [Version] version Version that contains the resource
          # @param [Hash] payload payload that contains response from Twilio
          
          # @return [CallInstance] CallInstance
          def initialize(version, payload)
            super(version)
          end
          
          ##
          # Access the events
          # @return [events] events
          def events
            @context.events
          end
          
          ##
          # Access the metrics
          # @return [metrics] metrics
          def metrics
            @context.metrics
          end
          
          ##
          # Access the summary
          # @return [summary] summary
          def summary
            @context.summary
          end
          
          ##
          # Provide a user friendly representation
          def to_s
            "<Twilio.Preview.Insights.CallInstance>"
          end
        end
      end
    end
  end
end